export const weatherAnims: { [key: string]: any } = {
	'Partly cloudy': require('../assets/animations/partlycloudy.json'),
	'Partly cloudy night': require('../assets/animations/partlycloudynight.json'),
	Sunny: require('../assets/animations/sunny.json'),
	Clear: require('../assets/animations/clear.json'),
	Cloudy: require('../assets/animations/cloudy.json'),
	Overcast: require('../assets/animations/cloudy.json'),
	Mist: require('../assets/animations/mist.json'),
	'Patchy rain possible': require('../assets/animations/moderaterain.json'),
	'Patchy snow possible': require('../assets/animations/moderatesnow.json'),
	'Patchy sleet possible': require('../assets/animations/sleet.json'),
	'Patchy freezing drizzle possible': require('../assets/animations/moderaterain.json'),
	'Thundery outbreaks possible': require('../assets/animations/thunder.json'),
	'Blowing snow': require('../assets/animations/moderatesnow.json'),
	Blizzard: require('../assets/animations/heavysnow.json'),
	Fog: require('../assets/animations/fog.json'),
	'Freezing fog': require('../assets/animations/fog.json'),
	'Patchy light drizzle': require('../assets/animations/moderaterain.json'),
	'Light drizzle': require('../assets/animations/drizzle.json'),
	'Freezing drizzle': require('../assets/animations/drizzle.json'),
	'Heavy freezing drizzle': require('../assets/animations/drizzle.json'),
	'Patchy light rain': require('../assets/animations/moderaterain.json'),
	'Light rain': require('../assets/animations/moderaterain.json'),
	'Moderate rain at times': require('../assets/animations/moderaterain.json'),
	'Moderate rain': require('../assets/animations/moderaterain.json'),
	'Heavy rain at times': require('../assets/animations/heavyrain.json'),
	'Heavy rain': require('../assets/animations/heavyrain.json'),
	'Light freezing rain': require('../assets/animations/drizzle.json'),
	'Moderate or heavy freezing rain': require('../assets/animations/heavyrain.json'),
	'Light sleet': require('../assets/animations/sleet.json'),
	'Moderate or heavy sleet': require('../assets/animations/sleet.json'),
	'Patchy light snow': require('../assets/animations/moderatesnow.json'),
	'Light snow': require('../assets/animations/moderatesnow.json'),
	'Patchy moderate snow': require('../assets/animations/moderatesnow.json'),
	'Moderate snow': require('../assets/animations/moderatesnow.json'),
	'Patchy heavy snow': require('../assets/animations/heavysnow.json'),
	'Heavy snow': require('../assets/animations/heavysnow.json'),
	'Ice pellets': require('../assets/animations/moderatesnow.json'),
	'Light rain shower': require('../assets/animations/moderaterain.json'),
	'Moderate or heavy rain shower': require('../assets/animations/heavyrain.json'),
	'Torrential rain shower': require('../assets/animations/rain.json'),
	'Light sleet showers': require('../assets/animations/sleet.json'),
	'Moderate or heavy sleet showers': require('../assets/animations/rain.json'),
	'Light snow showers': require('../assets/animations/moderatesnow.json'),
	'Moderate or heavy snow showers': require('../assets/animations/heavysnow.json'),
	'Light showers of ice pellets': require('../assets/animations/moderatesnow.json'),
	'Moderate or heavy showers of ice pellets': require('../assets/animations/heavysnow.json'),
	'Patchy light rain with thunder': require('../assets/animations/rainwiththunder.json'),
	'Moderate or heavy rain with thunder': require('../assets/animations/rainwiththunder.json'),
	'Patchy light snow with thunder': require('../assets/animations/moderatesnow.json'),
	'Moderate or heavy snow with thunder': require('../assets/animations/heavysnow.json'),
};
